-- ============================================================
-- Bibliothèque de menus (onglet Cuisine) — Domaine Sesquier
-- Colle dans :
-- https://supabase.com/dashboard/project/ymwebdihbmzrcaivldxu/sql/new
-- ============================================================

create table if not exists bibliotheque_menus (
  id bigint generated by default as identity primary key,
  type text not null default 'menu',   -- 'menu' | 'entree' | 'accompagnement'
  nom text not null default '',
  entree text,
  plat text,
  dessert text,
  ordre integer not null default 0,
  created_at timestamptz not null default now()
);

alter table bibliotheque_menus enable row level security;

create policy "allow_all_bibliotheque_menus" on bibliotheque_menus
  for all using (true) with check (true);
